apiVersion: v1
kind: Pod
metadata:
  name: admt-rebuild
  labels:
    tier: admt-api
spec:
  volumes:
    - name: bulk
      persistentVolumeClaim:
        claimName: argovis-bulk
  containers:
  - name: admt-rebuild
    imagePullPolicy: Always
    image: argovis/admtupdates:rebuild
    command: ['sleep', '10000000']
    env:
    - name: MONGODB_URI
      value: mongodb://database-admt/argo
    volumeMounts:
      - mountPath: "/bulk"
        name: bulk
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 6000Mi
        cpu: 3000m
  restartPolicy: Never

