apiVersion: v1
kind: Pod
metadata:
  name: admt-update
  labels:
    tier: admt-api
spec:
  volumes:
    - name: bulk
      persistentVolumeClaim:
        claimName: argovis-bulk
    - name: logs
      persistentVolumeClaim:
        claimName: logs
  containers:
  - name: admt-update
    imagePullPolicy: Always
    image: argovis/admtupdates:update
    env:
    - name: MONGODB_URI
      value: mongodb://database-admt/argo
    volumeMounts:
      - mountPath: "/bulk"
        name: bulk
      - mountPath: "/logs"
        name: logs
    resources:
      requests:
        memory: "2000Mi"
        cpu: "1000m"
      limits:
        memory: 2000Mi
        cpu: 1000m
  restartPolicy: Never